### PR TITLE
Updated Universal CSS

### PR DESCRIPTION
**Pull request by mpadil18**
Collaborated with Andrew to update CSS. Created classnames to be used across all files, fixing the issues seen in all pages after the merge.

Check out the [Style Guide here](https://docs.google.com/document/d/15iTS-sSEwhznEA2tuKtP_0Ogag22bCCyaY6X0pgSzFU/edit?usp=sharing) to see how the stylizing was optimized- the goal is to have these as universal components we can re-use later if we want (ex: if we want the user to fill in their progress for the day with a form input, we can use the `InputBubble` class.

One of the more noticable changes is changing the bubble color from `#FFF` to `#EEE`, and adding a `box-shadow` for visibility purposes. So any, and all feedback is encouraged!

### CODE REVIEW

**Review by ojalmaps — APPROVED** [review]
Looks good to me. Really great work on the style guide

**Review by ajmallon — APPROVED** [review]
Great work as always 👍

**Review by kbbeck — APPROVED** [review]
looks really good!

**Comment by annisanc** [comment]
Clean css to me, seems to improve responsiveness greatly

**Review by annisanc — APPROVED** [review]
Clean css to me, helps responsiveness greatly!

**Pull request merged**
